### ISSUE TITLE
Specific font google font styles do not work with custom fonts.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-text#108]
**How to recreate**

1. Add a placeholder
2. Add the Text Widget to that placeholder
3. Select a custom font, use https://fonts.googleapis.com/css?family=Raleway, type Raleway Regular in the text box.
4. Add another placeholder
5. Add the Text Widget to that placeholder
6. Select custom font, use https://fonts.googleapis.com/css?family=Raleway:900 typle Raleway Black in the text box.
7. Save and preview presentation.

**What happens**
The Text Widget with Raleway Regular will display the correct font, the Text Widget with Raleway Black will not.

**What should happen**
Both custom fonts should appear.

**Notes**
I've tried this with various fonts, the same results on each. For instance https://fonts.googleapis.com/css?family=Open+Sans works, and https://fonts.googleapis.com/css?family=Open+Sans:400,700 does not work.

**Comment by stulees** [comment]
@btfrise The Text Widget has a limitation with adding custom fonts in that you can't add a custom Google Font via our "Custom Font" selection and url entry. The reason is Google Fonts API provides CSS as the response for the request of the font, so we have a different mechanism for specifically adding Google Fonts to our text editor as opposed to custom fonts. 

Custom Fonts need to be the url to the actual font file (eg. .otf, ttf, etc). So you would have to download the Google font itself to your machine and upload it to a server location that you can then use for adding the custom font to the text editor. 

This issue can be closed. Thanks
