### ISSUE TITLE
Text Widget resetting font settings back to default on lines that don't contain any text

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-text#138]
**Describe the Bug**
If you change the font face and size in the Text Widget then add multiple rows of text separated by empty rows without text and save your changes, the font size and face will revert back to the default on the empty rows specifically.

**Reach**
So far 1 user, but affects anyone using the text widget.

**Impact**
The user is unable to get the desired spacing in the Text Widget because it keeps reverting the empty rows back to Verdana font size 11px.

**Expected behavior**
The Text Widget should maintain formatting for all text and empty space added.

**To Reproduce**
1. Create a test Presentation and add a placeholder with a Text Widget
2. Open the Text Widget and change the font size and font face.
3. Add multiple rows of text to the Widget and separate each row with a row that doesn't contain any text.
4. Save your changes then re-open the Text Widget
5. You'll notice the rows that don't contain any text have reverted to Verdana font with size 11px.
![image](https://user-images.githubusercontent.com/33877348/75924972-1c4f9580-5e25-11ea-9045-c4784581de0f.png)

**Comment by stulees** [comment]
@kaden-rise @sheadarlison I've looked into this and it appears to be formatting behaviour applied by TinyMCE, which is the JS WYSIWYG editor used for Text Settings. Upon initializing, for empty line breaks TinyMCE re-formats the line to strip out the custom `<span>` where font styling is applied and it becomes `<p>&nbsp;<br></p>` . Since it's missing the `<span>`, the styling that gets applied is TinyMCE default, not even the default we're applying (Verdana 24px), hence why the font size is 11px. 

There may be a hacky way around this, but I'm hesitant to invest the effort. It may create other unforeseen quirks as well as the version of TinyMCE being used in the widget settings is now a couple major versions behind, so documentation access is limited to these more recent versions. I thought about trying to upgrade the TinyMCE but that will result in more effort to adhere to their latest API.

It's not ideal, but a workaround is to highlight those empty line breaks and apply the font/size and resave. I've done this in this [presentation](https://apps.risevision.com/editor/workspace/feacc991-6cfc-4097-af08-102f713b45b3?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f) and it works. 

My opinion is we shouldn't invest time and effort to trying to hack in a solution. Widgets aren't our direction anymore.  Thoughts?

**Comment by kaden-rise** [comment]
@stulees The annoyance for the customer in this case is the fact that they have to apply that workaround. They often go back into their Presentation to make edits in the Text Widget and find that the rows with empty space have reverted back to Verdana size 11px. It makes it difficult for them to get the formatting they want whenever they have to go back and edit their Presentation. With that said, it's not an education user. @sheadarlison What do you think?

**Comment by sheadarlison** [comment]
@stulees what would the effort be to upgrade tinyMCE?

**Comment by stulees** [comment]
@sheadarlison Could be as easy as 1pt, but could be up to 5pts. Since it would be a couple major versions up, I'm not sure what API impact there would be on existing code in our Text settings or what changes have occurred in regards to Angular 1.x integration. The other thing is, there's no certainty it will resolve the problem as this issue seems intentional of TinyMCE.

**Comment by sheadarlison** [comment]
@stulees is 5pts about a week?

**Comment by stulees** [comment]
@sheadarlison 5pts is 2 - 3 days

**Comment by sheadarlison** [comment]
@stulees I'd like to invest up to 5pts in resolving this issue but it can wait until after the Twitter Epic is complete. The Text Widget is one of our most used Widgets so I think this investment is worth it.

Is that okay with you @kaden-rise?

**Comment by kaden-rise** [comment]
@sheadarlison That sounds good to me.

**Comment by stulees** [comment]
Not going to pursue this
