### ISSUE TITLE
Text editor won't open

### ISSUE THREAD

**Issue by leifottosson** [Rise-Vision/widget-text#163]
### What is the expected behavior from the user’s point of view? 
The text editor to open so I can enter text.

### What is the actual behavior from the user’s point of view? 
Text editor doesn't open. I only get a blank white popup window.

### What steps can be taken to reproduce the actual behavior?
Trying to opening it several times. Eventally it opens after many attempts to open it.

![screenshot 2022-10-23 180957](https://user-images.githubusercontent.com/5895269/197403117-341dcc21-5ade-40df-beb6-641208063b58.png)

**Comment by robb-price** [comment]
Hi Leif,

I spoke to our Dev team about this, and they are confident that this typically occurs when viewing the Blank Template Editor, and Text Widget settings in a region outside of North America or with a slower network speed. This is due to the large amount of Google Fonts that are loaded in the Widget settings, and unfortunately sometimes this can cause latency issues. At this time, we are not planning to invest in improving the situation as Widgets are considered a legacy product.

Normally, a refresh of the page will correct this, but again, depends on the network connection and reliability.

Thanks!
